{{- if .Values.loadBalancer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.tinkServer.name }}-lb
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.tinkServer.name }}-lb
  annotations:
    # ensures the service is created at the end
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
spec:
  type: LoadBalancer
  loadBalancerClass: {{ .Values.loadBalancer.class }}
  externalTrafficPolicy: Local
  ports:
  - name: {{ .Values.tinkServer.name }}
    port: {{ .Values.tinkServer.port.hostPort }}
    targetPort: {{ .Values.tinkServer.port.hostPort }}
    protocol: TCP
  - name: {{ .Values.hegel.name }}
    port: {{ .Values.hegel.port.hostPort }}
    targetPort: {{ .Values.hegel.port.hostPort }}
    protocol: TCP
  loadBalancerIP: {{ .Values.loadBalancer.ip }}
  selector:
    app: {{ .Values.tinkServer.name }}-lb
{{- end -}}
