namespace: tink-system
createNamespace: true

tinkController:
  deploy: true
  name: tink-controller-manager
  image: quay.io/tinkerbell/tink-controller:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  args: []
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-controller-manager-role
  roleBindingName: tink-controller-manager-rolebinding
  tinkLeaderElectionRoleName: tink-leader-election-role
  tinkLeaderElectionRoleBindingName: tink-leader-election-rolebinding

tinkServer:
  deploy: true
  name: tink-server
  image: quay.io/tinkerbell/tink:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  port:
    hostPortEnabled: false
    hostPort: 42113
  args: ["--tls=false"]
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  roleName: tink-server-role
  roleBindingName: tink-server-rolebinding
  loadBalancer:
    enabled: true
    ip: 192.168.2.101