{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.service.name }}
  name: {{ .Values.service.name }}-tcp
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  loadBalancerClass: {{ .Values.service.lbClass }}
  loadBalancerIP: {{ .Values.service.ip }}
  externalTrafficPolicy: Local
  ports:
  - name: {{ .Values.tinkData.name }} 
    port: {{ .Values.tinkData.deployment.port }}
    protocol: TCP
    targetPort: {{ .Values.tinkData.deployment.portName }}
  - name: {{ .Values.hegelData.name }} 
    port: {{ .Values.hegelData.deployment.port }}
    protocol: TCP
    targetPort: {{ .Values.hegelData.deployment.portName }}
  {{- if not .Values.boots.boots.hostNetwork }}
  {{- range .Values.bootsData.ports }}
  {{- if eq .protocol "TCP" }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
    protocol: {{ .protocol }}
  {{- end }}
  {{- end }}
  {{- end }}
  selector:
    {{- with .Values.service.tcp.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
