{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hegel-external-lb
  name: hegel-external-lb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  loadBalancerClass: {{ .Values.service.lbClass }}
  loadBalancerIP: {{ .Values.service.hegel.ip }}
  externalTrafficPolicy: Local
  ports:
  - name: {{ .Values.hegelData.name }} 
    port: {{ .Values.hegelData.deployment.port }}
    protocol: TCP
    targetPort: {{ .Values.hegelData.deployment.portName }}
  selector:
    app: hegel
{{- end -}}
